name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10

      # nix-shell используется для clang-format версии 10,
      # в которой появился параметр --dry-run,
      # используемый для тестирования.
      # В ubuntu-latest версия 9.
      - name: Проверка
        run: nix-shell --no-build-output --quiet ./.github --run ./.github/lint.sh

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Компиляция
        run: ./.github/build.sh
